# Uncomment the next line to define a global platform for your project

target 'BlackJack' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Google-Mobile-Ads-SDK'
  # Pods for BlackJack

  target 'BlackJackTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BlackJackUITests' do
    # Pods for testing
  end

end
