platform :ios, '13.0'
use_frameworks!

inhibit_all_warnings!

workspace 'BlackJack'

abstract_target 'CommonPods' do
  # Ads-related pods removed. Re-run `pod install` to update workspace pods.

  target 'BlackJack' do
    project 'BlackJack/BlackJack.xcodeproj'
  end

  target 'BlackJackTests' do
    project 'BlackJack/BlackJack.xcodeproj'
  end

  target 'BlackJackUITests' do
    project 'BlackJack/BlackJack.xcodeproj'
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'YES'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
      config.build_settings['SWIFT_VERSION'] ||= '5.0'
    end
  end
end
